server:
  port: 9009

spring:
  session:
    store-type: redis
  redis:
    database: 0
    #    host: 47.99.40.208
    host: 47.98.212.147
    port: 6379
    #    password: bysoft
    password: kevin123!
    pool:
      max-active: 1000 # 连接池最大连接数
      max-idle: 10 # 连接池最大空闲连接
      min-idle: 1 # 连接池最小空闲连接
      max-wait: -1
    timeout: 60000
# 服务注册配置
eureka:
  instance:
    non-secure-port: ${server.port:9009}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${eureka-server:localhost}:8761/eureka/

# 文件上传的绝对路径
upload:
  path: E:/dtms/files/uploadfile/
  staticPath: /dtms/files/**

doc:
  path: E:/dtms/files/doc/
  staticPath: /dtms/files/**

sqlbackup:
  path: E:/dtms/files/sql/
  staticPath: /dtms/files/**

geolite2:
  dbdir: E:/City/GeoLite2-City_20190903

