server:
  port: 9009

spring:
  session:
    store-type: redis
  redis:
    database: 0
    host: 47.99.40.208
    port: 6379
    password: bysoft
    pool:
      max-active: 1000 # 连接池最大连接数
      max-idle: 10 # 连接池最大空闲连接
      min-idle: 1 # 连接池最小空闲连接
      max-wait: -1
    timeout: 60000
# 服务注册配置
eureka:
  instance:
    non-secure-port: ${server.port:9009}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${eureka-server:localhost}:8761/eureka/

# 文件上传路径
upload:
  path: /home/dtms/files/uploadfile/
  staticPath: /dtms/files/**

# doc 文档保存路径
doc:
  path: /home/dtms/files/doc/
  staticPath: /dtms/files/**

# sql 文件备份路径
sqlbackup:
  path: /home/dtms/files/sql/
  staticPath: /dtms/files/**

geolite2:
  dbdir: /home/dtms/GeoLite2-City_20191022/