spring:
  application:
    name: entry-web
  zipkin:
    enabled: true
    base-url: http://localhost:9987 #修改为zipkin地址
  profiles:
    active: dev
  activiti:
    check-process-definitions: false
  http:
    multipart:
      max-file-size: 20MB
      max-request-size: 200MB

# 超时配置
zuul:
  max:
    host:
      connections: 60000
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 60000