server:
  port: 9001

spring:
  session:
    store-type: redis
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://47.98.212.147:3306/dtms?serverTimezone=Asia/Shanghai&characterEncoding=utf8&allowMultiQueries=true
#    username: root
#    password: Kevin123!
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.99.40.208:3306/dtms?serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: writer
    password: writer01@BY.cn
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    database: 0
    host: 47.99.40.208
    port: 6379
    password: bysoft
    pool:
      max-active: 1000 # 连接池最大连接数
      max-idle: 10 # 连接池最大空闲连接
      min-idle: 1 # 连接池最小空闲连接
      max-wait: -1
    timeout: 5000
#  rabbitmq:   # rabbitmq相关配置
#    host: localhost
#    port: 5672
#    username: xxx
#    password: xxx
# 服务注册配置
eureka:
  instance:
    non-secure-port: ${server.port:9001}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${eureka-server:localhost}:8761/eureka/

# 分布式id生成前置条件
snowflake:
  worker:
    id: 1
  datacenter:
    id: 1

#datasource:
#  default:
#    url: jdbc:mysql://47.98.212.147:3306/dtms?serverTimezone=Asia/Shanghai&characterEncoding=utf8&allowMultiQueries=true
#    username: root
#    password: Kevin123!
#  datasource2:
#    url: jdbc:mysql://47.98.212.147:3306/information_schema?serverTimezone=Asia/Shanghai&characterEncoding=utf8
#    username: root
#    password: Kevin123!