spring:
  application:
    name: service-dtms
  zipkin:
    enabled: true
    base-url: http://localhost:9987 #修改为zipkin地址
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath*:mapping/*.xml
  type-aliases-package: com.medical.dtms.service.dataobject

# 超时配置
zuul:
  max:
    host:
      connections: 500
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 60000